name: Linters and formatters

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Terraform linter
      run: |
        results=$(find . -type f -name "*.tf" ! -path "*/.terraform/*" -exec terraform fmt -check {} \;)
        if [ -n "$results" ]; then
          echo "Terraform files must be formatted with 'terraform fmt'. Please run 'terraform fmt' and commit the changes."
          echo "$results"
          exit 1
        fi
