name: Linters and formatters

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Terraform linter
      run: |
        terraform version
        results=$(find . -type f -name "*.tf" ! -path "*/.terraform/*" -exec terraform fmt -check {} \;)
        if [ -n "$results" ]; then
          echo "Terraform files must be formatted with 'terraform fmt'. Please run 'terraform fmt' and commit the changes."
          echo "$results"
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install yamllint
      run: pip install yamllint
    
    - name: YAML linter
      run: |
        results=$(find . -type f -name "*.yaml" -o -name "*.yml" -exec yamllint {} \;)
        if [ -n "$results" ]; then
          echo "YAML files must be formatted with 'yamllint'. Please run 'yamllint' and commit the changes."
          echo "$results"
          exit 1
        fi
